//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectionBoxService.WebTests
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/postbox");
            request1.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/postbox");
            request2.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/postbox");
            request3.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/postbox");
            request4.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/postbox");
            request5.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/postbox");
            request6.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/getboxes");
            request7.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/getboxes");
            request8.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/getboxes");
            request9.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/getboxes");
            request10.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/getboxes");
            request11.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            yield return request11;
            request11 = null;
        }
    }
}
