//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectionBoxService.WebTests
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using LibAyycorn.Dtos;
    using Newtonsoft.Json;
    using System.Linq;

    public class WebTest1Coded : WebTest
    {
        private string json;
        private List<Giftbox> Boxes;
        private readonly JsonSerializerSettings SerializerSettings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, MissingMemberHandling = MissingMemberHandling.Ignore };


        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
            json = System.IO.File.ReadAllText("../../../SelectionBoxService.WebTests/Data/selectionboxes.json");
            Boxes = JsonConvert.DeserializeObject<List<Giftbox>>(json, SerializerSettings);
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/getboxes");
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://ayycornselectionboxservice.azurewebsites.net/postbox");
            request2.Method = "POST";
            request2.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            StringHttpBody request2Body = new StringHttpBody();
            request2Body.ContentType = "application/json";
            request2Body.InsertByteOrderMark = false;
            request2Body.BodyString = JsonConvert.SerializeObject(Boxes.ElementAt(0));
            request2.Body = request2Body;
            yield return request2;
            request2 = null;
        }
    }
}
